Xray Test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -24,25 +24,42 @@ jobs:
       - run:
           name: Authenticate with Xray Cloud
           command: |
-            XRAY_TOKEN=$(curl -X POST https://xray.cloud.getxray.app/api/v2/authenticate \
+            RESPONSE=$(curl -X POST https://xray.cloud.getxray.app/api/v2/authenticate \
               -H "Content-Type: application/json" \
-              -d "{\"client_id\": \"$XRAY_CLIENT_ID\", \"client_secret\": \"$XRAY_CLIENT_SECRET\"}" | tr -d '"')
-            echo "export XRAY_TOKEN=$XRAY_TOKEN" >> $BASH_ENV
+              -d "{\"client_id\": \"$XRAY_CLIENT_ID\", \"client_secret\": \"$XRAY_CLIENT_SECRET\"}")
 
+            if [[ $RESPONSE == *"token"* ]]; then
+              XRAY_TOKEN=$(echo $RESPONSE | jq -r '.')
+              echo "export XRAY_TOKEN=$XRAY_TOKEN" >> $BASH_ENV
+              echo "✅ Xray authentication successful."
+            else
+              echo "❌ Xray authentication failed. Response: $RESPONSE"
+              exit 1
+            fi
+
+      # Upload Test Results to Xray Cloud
       - run:
           name: Upload Test Results to Xray Cloud
           command: |
-            # Ensure the report exists
-            if [ -f build/reports/cucumber/cucumber.json ]; then
+            REPORT_PATH="build/reports/cucumber/cucumber.json"
+
+            if [ -f "$REPORT_PATH" ]; then
               echo "Uploading test results to Xray Cloud..."
-              curl -X POST https://xray.cloud.getxray.app/api/v2/import/execution/cucumber \
+              RESPONSE=$(curl -X POST https://xray.cloud.getxray.app/api/v2/import/execution/cucumber \
                 -H "Content-Type: application/json" \
                 -H "Authorization: Bearer $XRAY_TOKEN" \
-                --data @build/reports/cucumber/cucumber.json
-              echo "✅ Test results uploaded to Jira Xray Cloud."
+                --data @"$REPORT_PATH")
+
+              if [[ $RESPONSE == *"key"* ]]; then
+                echo "✅ Test results uploaded successfully to Jira Xray Cloud."
+              else
+                echo "❌ Xray test upload failed. Response: $RESPONSE"
+                exit 1
+              fi
             else
               echo "❌ No test report found! Skipping Xray upload."
             fi
+
 
       - run:
           name: Install Argo CD CLI
